CREATE DATABASE Inmobiliaria
GO

USE Inmobiliaria

CREATE TABLE LOCALIDADES(
	ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL
)

CREATE TABLE UBICACIONES(
	ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	DIRECCION varchar(50) NOT NULL,
	IDLOCALIDAD int NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(ID),
)

CREATE TABLE TIPOS(
	ID int NOT NULL PRIMARY KEY IDENTITY(1,1),
	Nombre varchar(30) NOT NULL
)

CREATE TABLE DISPONIBILIDADES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(30) NOT NULL
)

CREATE TABLE USUARIOS(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	EMAIL VARCHAR(50) NOT NULL,
	CONTRASEÑA VARCHAR(20) NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(20) NOT NULL,
	DNI VARCHAR(10) NOT NULL
)

CREATE TABLE VENDEDORES(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	IDUSUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
)

CREATE TABLE INMUEBLES(
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IDTIPO INT NOT NULL FOREIGN KEY REFERENCES TIPOS(id),
	IDVENDEDOR INT FOREIGN KEY REFERENCES VENDEDORES(ID),
	IDUBICACION INT NOT NULL FOREIGN KEY REFERENCES UBICACIONES(ID),
	METROS2 INT NOT NULL,
	METROS2CUBIERTOS INT NOT NULL,
	IDDISPONIBILIDAD INT NOT NULL FOREIGN KEY REFERENCES DISPONIBILIDADES(ID),
	AMBIENTES INT NOT NULL,
	BAÑOS INT NOT NULL,
	PRECIO MONEY NOT NULL,
	DESCRIPCION VARCHAR(500) NOT NULL,
	ESTADO BIT NOT NULL DEFAULT 1,
)

CREATE TABLE IMAGENES(
	ID INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	IDPROPIEDAD INT FOREIGN KEY REFERENCES INMUEBLES(ID),
	URLIMAGEN VARCHAR(300) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
)